### ISSUE TITLE
Geeva storyline

### ISSUE THREAD

**Issue by lumbar527** [1010todd/Galactic-War#14]
### What this is for
I would like to help move this awesome plugin to completion, but I don't really know how the storylines should go.

### Some basic ideas for the Geeva storyline
- The player comes in contact with the ZIS
- The Kroom Kanai are involved
- The single Tarallion of the Geeva is in action
- The player gets a high salary so they can afford higher-tier ships
- The Geeva [come in contact with | are involved with] the Uoorn (because they're just "North-West" of the Geeva)
- The Kroom Kakaima become like the Kanai.

### Less general ideas
- The Geeva could reverse-engineer or upgrade (with the stuff they got from the ZIS) the powerful Golkar Torpedo.
- Discovering why the Kroom Kanai are different than the Kakaima. (Was it the ZIS? The Taroun? Some other race else? Just their own development?)
- A side storyline could involve helping the Kanai set up larger factories. (This could also maybe be something in a Dels storyline.)

**Comment by lumbar527** [comment]
I'm just going to throw out some more things here (if approved I'll start working on stuff):

**Intro-Start:**
1. Fend off the Kroom Kakaima in the already existing missions.
2. A Kakaima raiding party has attacked the edge planet where this stuff is offered. You hunt them down and retrieve valuable cargo.
3. A Geeva recruiter comes over to you and offers you a job helping them. You get a relatively small salary.
4. Now you are involved in the Geeva-Kroom war. Travel around fighting with a fleet.
5. How will anything make a difference in the war? You have some options:
- 1. Invade Kakaima space!
Lots more hard fighting. See **Kakaima Invasion** section.
- 2. Ask the ZIS for help.
No. See other options.
- 3. Use their tech/tech styles against them: steal and upgrade Golkar Torpedoes.
See **Golkar Collection** section.

**Kakaima Invasion** (In "middle" now)
1. Convince a "Great Leader" that there should be a great amassing of all the force to strike back. If you fail, repeat # 4 of **Intro-Start**.
2. You get to go around talking to people! Lots of traveling about to different Geeva planets.
3. Accompany the fleet to the starting point of the enterprise.
4. Work your way through the uninhabited systems and strike the first planet. Take it.
5. Keep going through few more planets.
6. You need supplies! Travel back to pick some stuff up. Also escort some freighters.
7. Escort retreating supply ships back to Geeva space because of a counter-counterattack made by the Kakaima.
8. Repeat # 7 for each of the claimed planets.
9. Kakaima are getting madder! Defend against a heavy attack fleet.
10. Hunt down and destroy the survivors.
11. Escort a large convoy away from the edge of the war. Systems are being conquered by the Kakaima.
12. Sneak through to enemy systems to try to spot tactical weaknesses.
13. Keep escorting ships and helping the retreat.
14. Last defense! The capital is under attack, and the Tarallion is launched. Even so, it should be a hard fight.
15. Help drive back remaining forces.
16. You're back where you started, basically.
17. Can't think of more yet.

**Golkar Collection (Minor Branch)**
1. Will work on later.

@1010todd, do you have your repo watched?

**Comment by 1010todd** [comment]
I have the repo watched but it often got lost in other notifications. 
Geeva wants stay on the defensive and focus on exploring the north for now to expand their territory and build more industries, for Geeva-Kroom war it might be dependent on Kroom-Dels conflict or Kroom-Erader conflict. At very least the Geeva would want to cooperate with Dels Dardornai to coordinate fronts and gain maximum advantage in the war pressing them in from all side.
* The Tarallion should never be used until the main Ultaka invasion.
* Kroom Kakaima will probably won't become like the Kanai, but they'll also be very hard to root out. Most likely the war would be interrupted by the Ultaka invasion or end in a stalemate shortly after that.
* Geeva is not interested in reverse engineering Golkar torpedo, might be more of Dels Dardornai thing.

**Comment by lumbar527** [comment]
OK, thanks. I just kind of want to contribute storyline stuff to the plugin. Do you want me to rewrite ideas for the storyline with your suggestion, or just let you handle storyline stuff?

**Comment by 1010todd** [comment]
I plan on working on Geeva storyline and already have a bit of it written a while ago. I think the other ones that I already started working on are Akralva, ZIS, Kumakk, and Uoorn.

**Comment by lumbar527** [comment]
Cool! Looking forward to playing then at some point!
